# Build a container image that has extra testing stuff in it, such
# as nushell, some preset logically bound images, etc. This expects
# to create an image derived FROM localhost/bootc which was created
# by the Dockerfile at top.

FROM scratch as context
# We only need this stuff in the initial context
COPY . /

# An intermediate layer which caches the extended RPMS
FROM localhost/bootc as extended
# And this layer has additional stuff for testing, such as nushell etc.
RUN --mount=type=bind,from=context,target=/run/context <<EORUN
set -xeuo pipefail
cd /run/context/
./provision-derived.sh
EORUN
